var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __decorateClass = (decorators, target, key, kind) => {
  var result = kind > 1 ? void 0 : kind ? __getOwnPropDesc(target, key) : target;
  for (var i = decorators.length - 1, decorator; i >= 0; i--)
    if (decorator = decorators[i])
      result = (kind ? decorator(target, key, result) : decorator(result)) || result;
  if (kind && result) __defProp(target, key, result);
  return result;
};
var __decorateParam = (index, decorator) => (target, key) => decorator(target, key, index);
import { IConfigurationService } from "../../../../../platform/configuration/common/configuration.js";
import { ITelemetryService } from "../../../../../platform/telemetry/common/telemetry.js";
import { TelemetryTrustedValue } from "../../../../../platform/telemetry/common/telemetryUtils.js";
import { ChatConfiguration } from "../../../chat/common/constants.js";
import { ShellIntegrationQuality } from "./toolTerminalCreator.js";
let RunInTerminalToolTelemetry = class {
  constructor(_telemetryService, _configurationService) {
    this._telemetryService = _telemetryService;
    this._configurationService = _configurationService;
  }
  logPrepare(state) {
    const subCommandsSanitized = state.subCommands.map((e) => {
      const commandName = e.split(" ")[0];
      let sanitizedCommandName = commandName.toLowerCase();
      if (!commandAllowList.has(sanitizedCommandName)) {
        if (/^(?:[A-Z][a-z0-9]+)+(?:-(?:[A-Z][a-z0-9]+))*$/.test(commandName)) {
          sanitizedCommandName = "(unknown:pwsh)";
        } else if (/^[a-z0-9_\-\.\\\/:;]+$/i.test(commandName)) {
          const properties = [];
          if (/[a-z]/.test(commandName)) {
            properties.push("ascii_lower");
          }
          if (/[A-Z]/.test(commandName)) {
            properties.push("ascii_upper");
          }
          if (/[0-9]/.test(commandName)) {
            properties.push("numeric");
          }
          const chars = [];
          for (const c of [".", "-", "_", "/", "\\", ":", ";"]) {
            if (commandName.includes(c)) {
              chars.push(c);
            }
          }
          sanitizedCommandName = `(unknown:${properties.join(",")}:${chars.join("")})`;
        } else if (/[^\x00-\x7F]/.test(commandName)) {
          sanitizedCommandName = "(unknown:unicode)";
        } else {
          sanitizedCommandName = "(unknown)";
        }
      }
      return sanitizedCommandName;
    });
    this._telemetryService.publicLog2("toolUse.runInTerminal.prepare", {
      terminalToolSessionId: state.terminalToolSessionId,
      subCommands: new TelemetryTrustedValue(JSON.stringify(subCommandsSanitized)),
      autoApproveAllowed: state.autoApproveAllowed,
      autoApproveResult: state.autoApproveResult,
      autoApproveReason: state.autoApproveReason,
      autoApproveDefault: state.autoApproveDefault
    });
  }
  logInvoke(instance, state) {
    this._telemetryService.publicLog2("toolUse.runInTerminal", {
      terminalSessionId: instance.sessionId,
      terminalToolSessionId: state.terminalToolSessionId,
      result: state.error ?? "success",
      strategy: state.shellIntegrationQuality === ShellIntegrationQuality.Rich ? 2 : state.shellIntegrationQuality === ShellIntegrationQuality.Basic ? 1 : 0,
      userEditedCommand: state.didUserEditCommand ? 1 : 0,
      toolEditedCommand: state.didToolEditCommand ? 1 : 0,
      isBackground: state.isBackground ? 1 : 0,
      isNewSession: state.isNewSession ? 1 : 0,
      isSandbox: state.isSandboxWrapped ? 1 : 0,
      requestUnsandboxedExecutionReason: state.requestUnsandboxedExecutionReason,
      outputLineCount: state.outputLineCount,
      nonZeroExitCode: state.exitCode === void 0 ? -1 : state.exitCode === 0 ? 0 : 1,
      exitCodeValue: state.exitCode ?? -1,
      timingConnectMs: state.timingConnectMs,
      timingExecuteMs: state.timingExecuteMs,
      pollDurationMs: state.pollDurationMs ?? 0,
      terminalExecutionIdleBeforeTimeout: state.terminalExecutionIdleBeforeTimeout ?? false,
      inputUserChars: state.inputUserChars,
      inputUserSigint: state.inputUserSigint,
      inputToolManualAcceptCount: state.inputToolManualAcceptCount ?? 0,
      inputToolManualRejectCount: state.inputToolManualRejectCount ?? 0,
      inputToolManualChars: state.inputToolManualChars ?? 0,
      inputToolManualShownCount: state.inputToolManualShownCount ?? 0,
      inputToolFreeFormInputShownCount: state.inputToolFreeFormInputShownCount ?? 0,
      inputToolFreeFormInputCount: state.inputToolFreeFormInputCount ?? 0,
      compressOutputEnabled: this._configurationService.getValue(ChatConfiguration.CompressOutputEnabled) === true
    });
  }
  /**
   * Reports the measurements produced by the terminal output compaction
   * {@link Report}, so the effectiveness of compaction (how much output was
   * removed and whether it was lossless) can be evaluated across sessions.
   */
  logCompaction(report) {
    this._telemetryService.publicLog2("toolUse.runInTerminal.compaction", {
      commandKinds: new TelemetryTrustedValue(JSON.stringify(report.commandKinds)),
      originalChars: report.original.chars,
      compactedChars: report.compacted.chars
    });
  }
  logCompactionFailed() {
    this._telemetryService.publicLog2("toolUse.runInTerminal.compactionFailed", {});
  }
};
RunInTerminalToolTelemetry = __decorateClass([
  __decorateParam(0, ITelemetryService),
  __decorateParam(1, IConfigurationService)
], RunInTerminalToolTelemetry);
const commandAllowList = /* @__PURE__ */ new Set([
  // Special chars/scripting
  "!",
  "@",
  "#",
  "$",
  "%",
  "^",
  "&",
  "*",
  "(",
  ")",
  "~",
  "{",
  "}",
  "<",
  ">",
  // Utils
  ".",
  "7z",
  "alias",
  "assoc",
  "attrib",
  "awk",
  "basename",
  "bg",
  "blkid",
  "bunzip2",
  "bzip2",
  "cat",
  "cd",
  "certutil",
  "chkdsk",
  "chmod",
  "chown",
  "cipher",
  "clear",
  "cls",
  "cmp",
  "column",
  "comm",
  "compact",
  "compress",
  "copy",
  "cp",
  "curl",
  "cut",
  "date",
  "dd",
  "del",
  "df",
  "diff",
  "dig",
  "dir",
  "dirname",
  "diskpart",
  "dism",
  "disown",
  "du",
  "echo",
  "env",
  "erase",
  "eval",
  "expand",
  "export",
  "fc",
  "fdisk",
  "fg",
  "file",
  "find",
  "findstr",
  "fmt",
  "fold",
  "forfiles",
  "format",
  "free",
  "fsck",
  "git",
  "gpupdate",
  "grep",
  "groupadd",
  "groups",
  "gunzip",
  "gzip",
  "hash",
  "head",
  "hexdump",
  "history",
  "host",
  "htop",
  "icacls",
  "id",
  "ifconfig",
  "iostat",
  "ip",
  "ipconfig",
  "iptables",
  "jobs",
  "jq",
  "kill",
  "killall",
  "less",
  "ln",
  "locate",
  "ls",
  "lsblk",
  "lscpu",
  "lsof",
  "man",
  "mkdir",
  "mklink",
  "more",
  "mount",
  "move",
  "mv",
  "nbtstat",
  "nc/netcat",
  "net",
  "netstat",
  "nice",
  "nl",
  "nohup",
  "nslookup",
  "nslookup",
  "od",
  "passwd",
  "paste",
  "pathping",
  "pause",
  "pgrep",
  "ping",
  "pkill",
  "powercfg",
  "pr",
  "printenv",
  "ps",
  "pwd",
  "query",
  "rar",
  "readlink",
  "realpath",
  "reg",
  "rem",
  "ren",
  "rename",
  "renice",
  "rev",
  "rm",
  "rmdir",
  "robocopy",
  "route",
  "rsync",
  "sc",
  "schtasks",
  "scp",
  "sed",
  "seq",
  "set",
  "setx",
  "sfc",
  "shred",
  "shuf",
  "shutdown",
  "sleep",
  "sort",
  "source",
  "split",
  "ss",
  "ssh",
  "stat",
  "strings",
  "su",
  "subst",
  "sudo",
  "systeminfo",
  "tac",
  "tail",
  "tar",
  "tee",
  "telnet",
  "test",
  "time",
  "top",
  "touch",
  "tr",
  "traceroute",
  "tracert",
  "tree",
  "true",
  "truncate",
  "type",
  "type",
  "umask",
  "umount",
  "unalias",
  "uname",
  "uncompress",
  "unexpand",
  "uniq",
  "unlink",
  "unrar",
  "unzip",
  "uptime",
  "useradd",
  "usermod",
  "vmstat",
  "vol",
  "watch",
  "wc",
  "wget",
  "where",
  "whereis",
  "which",
  "who",
  "whoami",
  "wmic",
  "xargs",
  "xcopy",
  "xxd",
  "xz",
  "yes",
  "zcat",
  "zip",
  "zless",
  "zmore",
  // SCM
  "bitbucket",
  "bzr",
  "cvs",
  "gh",
  "git",
  "glab",
  "hg",
  "svn",
  "fossil",
  "p4",
  // Devtools, languages, package manager
  "adb",
  "ansible",
  "apk",
  "apt-get",
  "apt",
  "aws",
  "az",
  "brew",
  "bundle",
  "cargo",
  "choco",
  "clang",
  "cmake",
  "composer",
  "conan",
  "conda",
  "dnf",
  "docker-compose",
  "docker",
  "dotnet",
  "emacs",
  "esbuild",
  "eslint",
  "flatpak",
  "flutter",
  "fnm",
  "g++",
  "gcc",
  "gcloud",
  "go",
  "gradle",
  "helm",
  "java",
  "javac",
  "jest",
  "julia",
  "kotlin",
  "kubectl",
  "lua",
  "make",
  "mocha",
  "mvn",
  "n",
  "nano",
  "node",
  "npm",
  "nvm",
  "pacman",
  "perl",
  "php",
  "phpunit",
  "pip",
  "pipenv",
  "pnpm",
  "pod",
  "podman",
  "poetry",
  "python",
  "r",
  "rollup",
  "ruby",
  "rustc",
  "rustup",
  "snap",
  "swift",
  "terraform",
  "tsc",
  "tslint",
  "vagrant",
  "vcpkg",
  "vi",
  "vim",
  "vite",
  "vitest",
  "webpack",
  "yarn",
  "yum",
  "zypper",
  // AI tools
  "aider",
  "amp",
  "claude",
  "codex",
  "copilot",
  "gemini",
  "toad",
  "q",
  // Misc Windows executables
  "taskkill",
  "taskkill.exe",
  // PowerShell
  "add-content",
  "compare-object",
  "convertfrom-json",
  "convertto-json",
  "copy-item",
  "format-custom",
  "format-list",
  "format-table",
  "format-wide",
  "get-childitem",
  "get-command",
  "get-content",
  "get-date",
  "get-help",
  "get-location",
  "get-process",
  "get-random",
  "get-service",
  "invoke-expression",
  "invoke-restmethod",
  "invoke-webrequest",
  "join-path",
  "measure-command",
  "measure-object",
  "move-item",
  "new-item",
  "out-file",
  "remove-item",
  "restart-computer",
  "select-object",
  "select-string",
  "select-xml",
  "set-acl",
  "set-content",
  "set-itemproperty",
  "sort-object",
  "split-path",
  "start-process",
  "start-sleep",
  "stop-process",
  "test-path",
  "write-host",
  "write-output",
  // PowerShell aliases
  "iex",
  "irm",
  "iwr",
  "rd",
  "ri",
  "sp",
  "spps"
]);
export {
  RunInTerminalToolTelemetry
};
