const PROMPT_TIMELINE_CONTRIB_ID = "chat.promptTimeline";
const PROMPT_TIMELINE_DISPLAY_SETTING = "sessions.chatTimeline.display";
const PROMPT_TIMELINE_STICKY_SCROLL_SETTING = "chat.stickyScroll.enabled";
const PROMPT_TIMELINE_RAIL_STYLES = ["off", "ruler", "gutter"];
const MIN_PROMPTS = 2;
export {
  MIN_PROMPTS,
  PROMPT_TIMELINE_CONTRIB_ID,
  PROMPT_TIMELINE_DISPLAY_SETTING,
  PROMPT_TIMELINE_RAIL_STYLES,
  PROMPT_TIMELINE_STICKY_SCROLL_SETTING
};
