var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __decorateClass = (decorators, target, key, kind) => {
  var result = kind > 1 ? void 0 : kind ? __getOwnPropDesc(target, key) : target;
  for (var i = decorators.length - 1, decorator; i >= 0; i--)
    if (decorator = decorators[i])
      result = (kind ? decorator(target, key, result) : decorator(result)) || result;
  if (kind && result) __defProp(target, key, result);
  return result;
};
var __decorateParam = (index, decorator) => (target, key) => decorator(target, key, index);
import { safeSetInnerHtml } from "../../../../base/browser/domSanitize.js";
import { createStyleSheet } from "../../../../base/browser/domStylesheets.js";
import { getMenuWidgetCSS, Menu, unthemedMenuStyles } from "../../../../base/browser/ui/menu/menu.js";
import { Disposable, DisposableStore } from "../../../../base/common/lifecycle.js";
import { isLinux, isWindows } from "../../../../base/common/platform.js";
import Severity from "../../../../base/common/severity.js";
import { localize } from "../../../../nls.js";
import { IMenuService, MenuId } from "../../../../platform/actions/common/actions.js";
import { IClipboardService } from "../../../../platform/clipboard/common/clipboardService.js";
import { IContextKeyService } from "../../../../platform/contextkey/common/contextkey.js";
import { IDialogService } from "../../../../platform/dialogs/common/dialogs.js";
import { ExtensionIdentifier, ExtensionIdentifierSet } from "../../../../platform/extensions/common/extensions.js";
import { IInstantiationService } from "../../../../platform/instantiation/common/instantiation.js";
import { ILogService } from "../../../../platform/log/common/log.js";
import { IOpenerService } from "../../../../platform/opener/common/opener.js";
import product from "../../../../platform/product/common/product.js";
import { AuxiliaryWindowMode, IAuxiliaryWindowService } from "../../../services/auxiliaryWindow/browser/auxiliaryWindowService.js";
import { IHostService } from "../../../services/host/browser/host.js";
import { IssueSource } from "../common/issue.js";
import { normalizeGitHubUrl } from "../common/issueReporterUtil.js";
import BaseHtml from "./issueReporterPage.js";
import { IssueWebReporter } from "./issueReporterService.js";
import { IGitHubUploadService } from "./githubUploadService.js";
import { IFileService } from "../../../../platform/files/common/files.js";
import { IEditorService } from "../../../services/editor/common/editorService.js";
import { URI } from "../../../../base/common/uri.js";
import { LRUCache } from "../../../../base/common/map.js";
import { hash } from "../../../../base/common/hash.js";
import { decodeBase64 } from "../../../../base/common/buffer.js";
import "./media/issueReporter.css";
const MAX_URL_LENGTH = 7500;
const GENERATED_BY_ISSUE_REPORTER_MARKER = "<!-- generated by issue reporter -->";
const ISSUE_DATA_ATTACHMENT_NAME = "issue-data.md";
function extractIssueData(issueBody) {
  const detailsBlocks = [];
  const bodyParts = [];
  const detailsTag = /<details\b[^>]*>|<\/details\s*>/gi;
  let depth = 0;
  let blockStart = 0;
  let bodyStart = 0;
  let match;
  while (match = detailsTag.exec(issueBody)) {
    if (match[0].startsWith("</")) {
      if (depth === 0) {
        continue;
      }
      depth--;
      if (depth === 0) {
        detailsBlocks.push(issueBody.slice(blockStart, detailsTag.lastIndex).trim());
        bodyParts.push(issueBody.slice(bodyStart, blockStart));
        bodyStart = detailsTag.lastIndex;
      }
    } else {
      if (depth === 0) {
        blockStart = match.index;
      }
      depth++;
    }
  }
  if (!detailsBlocks.length) {
    return void 0;
  }
  bodyParts.push(issueBody.slice(bodyStart));
  return {
    body: bodyParts.join("\n\n").replace(/\n{3,}/g, "\n\n").trimEnd(),
    fileContent: `# ${localize("issueData", "Issue Data")}

${detailsBlocks.join("\n\n")}
`
  };
}
let IssueFormService = class extends Disposable {
  constructor(instantiationService, auxiliaryWindowService, menuService, contextKeyService, logService, dialogService, hostService, openerService, fileService, githubUploadService, editorService, clipboardService) {
    super();
    this.instantiationService = instantiationService;
    this.auxiliaryWindowService = auxiliaryWindowService;
    this.menuService = menuService;
    this.contextKeyService = contextKeyService;
    this.logService = logService;
    this.dialogService = dialogService;
    this.hostService = hostService;
    this.openerService = openerService;
    this.fileService = fileService;
    this.githubUploadService = githubUploadService;
    this.editorService = editorService;
    this.clipboardService = clipboardService;
    this.issueReporterWindow = null;
    this.extensionIdentifierSet = new ExtensionIdentifierSet();
    this.arch = "";
    this.release = "";
    this.type = "";
    /** Bounded cache of already-uploaded attachments to avoid re-uploading on retry within a session. Uses a content hash so large data URLs aren't retained as keys. */
    this.uploadCache = new LRUCache(32);
  }
  async openReporter(data) {
    if (this.hasToReload(data)) {
      return;
    }
    return this.openAuxIssueReporterLegacy(data);
  }
  async submitIssue(host, data, title, body) {
    const screenshots = host.getScreenshots();
    const recordings = host.getRecordings();
    const issueTarget = this.getIssueTarget(data);
    if (!issueTarget?.url) {
      return false;
    }
    if (issueTarget.external) {
      return this.openerService.open(issueTarget.url, { openExternal: true });
    }
    const gitHubDetails = this.parseGitHubUrl(issueTarget.url);
    let repoId;
    const resolveRepoId = async () => {
      if (!gitHubDetails) {
        return void 0;
      }
      repoId ??= await this.githubUploadService.resolveRepositoryId(gitHubDetails.owner, gitHubDetails.repositoryName, data.githubAccessToken);
      return repoId;
    };
    let mediaMarkdown = "";
    const hasAttachments = screenshots.length > 0 || recordings.length > 0;
    if (hasAttachments && data.githubAccessToken && gitHubDetails) {
      host.setUploading(true);
      try {
        const filesToProcess = [];
        for (let i = 0; i < screenshots.length; i++) {
          const dataUrl = screenshots[i].annotatedDataUrl ?? screenshots[i].dataUrl;
          const bytes = this.dataUrlToBytes(dataUrl);
          if (bytes) {
            const isJpeg = dataUrl.startsWith("data:image/jpeg");
            const extension = isJpeg ? "jpg" : "png";
            const contentType = isJpeg ? "image/jpeg" : "image/png";
            filesToProcess.push({ key: `screenshot:${hash(dataUrl)}`, name: `screenshot-${i + 1}.${extension}`, bytes, contentType });
          }
        }
        for (let i = 0; i < recordings.length; i++) {
          const rec = recordings[i];
          const fileContent = await this.fileService.readFile(URI.file(rec.filePath));
          const ext = rec.filePath.endsWith(".mp4") ? "mp4" : "webm";
          const contentType = ext === "mp4" ? "video/mp4" : "video/webm";
          filesToProcess.push({ key: `recording:${rec.filePath}`, name: `recording-${i + 1}.${ext}`, bytes: fileContent.value.buffer, contentType });
        }
        if (filesToProcess.length > 0) {
          for (let i = 0; i < filesToProcess.length; i++) {
            host.setAttachmentUploadState(i, "pending");
          }
          const uploadResults = [];
          for (let i = 0; i < filesToProcess.length; i++) {
            const file = filesToProcess[i];
            const cached = this.uploadCache.get(file.key);
            if (cached) {
              uploadResults.push(cached);
              host.setAttachmentUploadState(i, "done");
              continue;
            }
            const resolvedRepoId = await resolveRepoId();
            if (!resolvedRepoId) {
              throw new Error("No GitHub repository resolved for attachment upload.");
            }
            host.setAttachmentUploadState(i, "uploading");
            const [result] = await this.githubUploadService.uploadViaMobileApi(
              data.githubAccessToken,
              resolvedRepoId,
              [file]
            );
            if (!result) {
              throw new Error(`Upload returned no result for ${file.name}.`);
            }
            this.uploadCache.set(file.key, result);
            uploadResults.push(result);
            host.setAttachmentUploadState(i, "done");
          }
          mediaMarkdown = `

### ${localize("issueReporter.attachmentsHeading", "Attachments")}

`;
          for (const r of uploadResults) {
            mediaMarkdown += r.contentType.startsWith("video/") ? `${r.assetUrl}

` : `![${r.fileName}](${r.assetUrl})

`;
          }
        }
      } catch (err) {
        this.logService.error("[IssueFormService] Upload failed:", err);
        mediaMarkdown = `

### ${localize("issueReporter.attachmentsHeading", "Attachments")}

> ${localize("issueReporter.attachmentsUploadFailed", "Upload failed. Please drag and drop attachments manually.")}

`;
      } finally {
        host.setUploading(false);
      }
    }
    const issueBody = body + mediaMarkdown;
    const baseUrl = this.getIssueUrlWithTitle(title, issueTarget.url);
    let previewBody = issueBody;
    let url = this.createIssuePreviewUrl(baseUrl, previewBody, gitHubDetails, data.issueSource);
    if (url.length > MAX_URL_LENGTH && data.githubAccessToken && gitHubDetails) {
      const shortenedBody = await this.tryCreateBodyWithIssueDataAttachment(host, issueBody, baseUrl, gitHubDetails, data.issueSource, data.githubAccessToken, resolveRepoId);
      if (shortenedBody) {
        previewBody = shortenedBody;
        url = this.createIssuePreviewUrl(baseUrl, previewBody, gitHubDetails, data.issueSource);
      }
    }
    if (url.length > MAX_URL_LENGTH) {
      const shouldWrite = await this.showClipboardDialog();
      if (!shouldWrite) {
        return false;
      }
      try {
        await this.clipboardService.writeText(issueBody);
      } catch (error) {
        this.logService.error("Writing issue data to clipboard failed", error);
        return false;
      }
      url = this.createIssuePreviewUrl(baseUrl, localize("pasteData", "We have written the needed data into your clipboard because it was too large to send. Please paste."), gitHubDetails, data.issueSource);
    }
    const uri = URI.parse(url);
    const skipValidation = uri.scheme === "https" && uri.authority === "github.com";
    return this.openerService.open(url, { openExternal: true, skipValidation });
  }
  async tryCreateBodyWithIssueDataAttachment(host, issueBody, baseUrl, gitHubDetails, issueSource, githubAccessToken, resolveRepoId) {
    const extracted = extractIssueData(issueBody);
    if (!extracted) {
      return void 0;
    }
    host.setUploading(true);
    try {
      const repoId = await resolveRepoId();
      if (!repoId) {
        return void 0;
      }
      const result = await this.uploadIssueDataFile(githubAccessToken, repoId, extracted.fileContent);
      const bodyWithLink = this.createBodyWithIssueDataLink(extracted.body, result.assetUrl);
      if (this.createIssuePreviewUrl(baseUrl, bodyWithLink, gitHubDetails, issueSource).length > MAX_URL_LENGTH) {
        return void 0;
      }
      return bodyWithLink;
    } catch (error) {
      this.logService.error("Uploading issue data attachment failed", error);
      return void 0;
    } finally {
      host.setUploading(false);
    }
  }
  async uploadIssueDataFile(githubAccessToken, repoId, fileContent) {
    const key = `${ISSUE_DATA_ATTACHMENT_NAME}:${hash(fileContent)}`;
    const cached = this.uploadCache.get(key);
    if (cached) {
      return cached;
    }
    const file = {
      key,
      name: ISSUE_DATA_ATTACHMENT_NAME,
      bytes: new TextEncoder().encode(fileContent),
      contentType: "text/plain"
    };
    const [result] = await this.githubUploadService.uploadViaMobileApi(githubAccessToken, repoId, [file]);
    if (!result) {
      throw new Error("Issue data upload did not return a result.");
    }
    this.uploadCache.set(key, result);
    return result;
  }
  createBodyWithIssueDataLink(body, issueDataUrl) {
    const attachmentMarkdown = `

### ${localize("additionalIssueData", "Additional Issue Data")}

[${ISSUE_DATA_ATTACHMENT_NAME}](${issueDataUrl})`;
    const markerIndex = body.indexOf(GENERATED_BY_ISSUE_REPORTER_MARKER);
    if (markerIndex === -1) {
      return `${body.trimEnd()}${attachmentMarkdown}
`;
    }
    return `${body.slice(0, markerIndex).trimEnd()}${attachmentMarkdown}

${body.slice(markerIndex).trimStart()}`;
  }
  createIssuePreviewUrl(baseUrl, body, gitHubDetails, issueSource) {
    const url = `${baseUrl}&body=${encodeURIComponent(body)}`;
    return this.addTemplateToUrl(url, gitHubDetails?.owner, gitHubDetails?.repositoryName, issueSource);
  }
  getIssueTarget(data) {
    const selectedExtension = this.getSelectedExtension(data);
    if (data.issueSource === IssueSource.Extension && selectedExtension) {
      const extensionUrl = this.getExtensionIssueUrl(selectedExtension);
      if (!extensionUrl) {
        return void 0;
      }
      return { url: extensionUrl, external: !this.isGitHubUrl(extensionUrl) };
    }
    if (data.issueSource === IssueSource.Marketplace) {
      const marketplaceIssueUrl = product.reportMarketplaceIssueUrl ?? product.reportIssueUrl;
      return marketplaceIssueUrl ? { url: marketplaceIssueUrl, external: false } : void 0;
    }
    if (data.uri) {
      const url = URI.revive(data.uri).toString();
      return { url, external: !this.isGitHubUrl(url) };
    }
    if (data.privateUri) {
      const url = URI.revive(data.privateUri).toString();
      return { url, external: !this.isGitHubUrl(url) };
    }
    return product.reportIssueUrl ? { url: product.reportIssueUrl, external: false } : void 0;
  }
  getSelectedExtension(data) {
    return data.extensionId ? data.enabledExtensions.find((ext) => ext.id.toLowerCase() === data.extensionId?.toLowerCase()) : void 0;
  }
  getExtensionIssueUrl(extension) {
    if (extension.uri) {
      return URI.revive(extension.uri).toString();
    }
    if (extension.bugsUrl && /^https?:\/\/github\.com\/([^\/]*)\/([^\/]*)\/?(\/issues)?\/?$/.test(extension.bugsUrl)) {
      return `${normalizeGitHubUrl(extension.bugsUrl)}/issues/new`;
    }
    if (extension.repositoryUrl && /^https?:\/\/github\.com\/([^\/]*)\/([^\/]*)\/?$/.test(extension.repositoryUrl)) {
      return `${normalizeGitHubUrl(extension.repositoryUrl)}/issues/new`;
    }
    return extension.bugsUrl || extension.repositoryUrl;
  }
  isGitHubUrl(url) {
    return /^https?:\/\/github\.com\//i.test(url);
  }
  parseGitHubUrl(url) {
    const match = /^https?:\/\/github\.com\/([^\/?#]+)\/([^\/?#]+).*/i.exec(url);
    if (!match) {
      return void 0;
    }
    return { owner: match[1], repositoryName: match[2] };
  }
  getIssueUrlWithTitle(issueTitle, issueUrl) {
    if (this.isGitHubUrl(issueUrl) && !/\/issues\/new(?:[?#].*)?$/i.test(issueUrl)) {
      issueUrl = `${normalizeGitHubUrl(issueUrl)}/issues/new`;
    }
    const queryStringPrefix = issueUrl.indexOf("?") === -1 ? "?" : "&";
    return `${issueUrl}${queryStringPrefix}title=${encodeURIComponent(issueTitle)}`;
  }
  addTemplateToUrl(baseUrl, owner, repositoryName, issueSource) {
    const needsTemplate = issueSource === IssueSource.VSCode || issueSource === IssueSource.AgentsWindow || owner?.toLowerCase() === "microsoft" && repositoryName?.toLowerCase() === "vscode";
    if (!needsTemplate) {
      return baseUrl;
    }
    try {
      const url = new URL(baseUrl);
      url.searchParams.set("template", "bug_report.md");
      return url.toString();
    } catch {
      return `${baseUrl}&template=bug_report.md`;
    }
  }
  dataUrlToBytes(dataUrl) {
    const commaIndex = dataUrl.indexOf(",");
    if (commaIndex === -1) {
      return void 0;
    }
    try {
      return decodeBase64(dataUrl.substring(commaIndex + 1)).buffer;
    } catch {
      return void 0;
    }
  }
  /** Opens the classic non-wizard reporter in an auxiliary window. */
  async openAuxIssueReporterLegacy(data) {
    await this.openAuxIssueReporter(data);
    if (this.issueReporterWindow) {
      const issueReporter = this.instantiationService.createInstance(IssueWebReporter, false, data, { type: this.type, arch: this.arch, release: this.release }, product, this.issueReporterWindow);
      issueReporter.render();
    }
  }
  async openAuxIssueReporter(data, bounds) {
    let issueReporterBounds = { width: 700, height: 800 };
    if (bounds && typeof bounds.x === "number" && typeof bounds.y === "number") {
      const centerX = bounds.x + bounds.width / 2;
      const centerY = bounds.y + bounds.height / 2;
      issueReporterBounds = { ...issueReporterBounds, x: centerX - 350, y: centerY - 400 };
    }
    const disposables = new DisposableStore();
    const auxiliaryWindow = disposables.add(await this.auxiliaryWindowService.open({ mode: AuxiliaryWindowMode.Normal, bounds: issueReporterBounds, nativeTitlebar: true, disableFullscreen: true }));
    const platformClass = isWindows ? "windows" : isLinux ? "linux" : "mac";
    if (auxiliaryWindow) {
      await auxiliaryWindow.whenStylesHaveLoaded;
      auxiliaryWindow.window.document.title = "Issue Reporter";
      auxiliaryWindow.window.document.body.classList.add("issue-reporter-body", "monaco-workbench", platformClass);
      auxiliaryWindow.container.remove();
      if (!Menu.globalStyleSheet) {
        const menuStyleSheet = createStyleSheet(auxiliaryWindow.window.document.head);
        menuStyleSheet.textContent = getMenuWidgetCSS(unthemedMenuStyles, false);
      }
      const div = document.createElement("div");
      div.classList.add("monaco-workbench");
      auxiliaryWindow.window.document.body.appendChild(div);
      safeSetInnerHtml(div, BaseHtml(), {
        // Also allow input elements
        allowedTags: {
          augment: [
            "input",
            "select",
            "checkbox",
            "textarea"
          ]
        },
        allowedAttributes: {
          augment: [
            "id",
            "class",
            "style",
            "textarea"
          ]
        }
      });
      this.issueReporterWindow = auxiliaryWindow.window;
    } else {
      console.error("Failed to open auxiliary window");
      disposables.dispose();
    }
    this.issueReporterWindow?.addEventListener("beforeunload", () => {
      auxiliaryWindow.window.close();
      disposables.dispose();
      this.issueReporterWindow = null;
    });
  }
  async sendReporterMenu(extensionId) {
    const menu = this.menuService.createMenu(MenuId.IssueReporter, this.contextKeyService);
    const actions = menu.getActions({ renderShortTitle: true }).flatMap((entry) => entry[1]);
    for (const action of actions) {
      try {
        if (action.item && "source" in action.item && action.item.source?.id.toLowerCase() === extensionId.toLowerCase()) {
          this.extensionIdentifierSet.add(extensionId.toLowerCase());
          await action.run();
        }
      } catch (error) {
        console.error(error);
      }
    }
    if (!this.extensionIdentifierSet.has(extensionId)) {
      return void 0;
    }
    this.extensionIdentifierSet.delete(new ExtensionIdentifier(extensionId));
    menu.dispose();
    const result = this.currentData;
    this.currentData = void 0;
    return result ?? void 0;
  }
  //#region used by issue reporter
  async closeReporter() {
    this.issueReporterWindow?.close();
  }
  async reloadWithExtensionsDisabled() {
    if (this.issueReporterWindow) {
      try {
        await this.hostService.reload({ disableExtensions: true });
      } catch (error) {
        this.logService.error(error);
      }
    }
  }
  async showConfirmCloseDialog() {
    await this.dialogService.prompt({
      type: Severity.Warning,
      message: localize("confirmCloseIssueReporter", "Your input will not be saved. Are you sure you want to close this window?"),
      buttons: [
        {
          label: localize({ key: "yes", comment: ["&& denotes a mnemonic"] }, "&&Yes"),
          run: () => {
            this.closeReporter();
            this.issueReporterWindow = null;
          }
        },
        {
          label: localize("cancel", "Cancel"),
          run: () => {
          }
        }
      ]
    });
  }
  async showClipboardDialog() {
    let result = false;
    await this.dialogService.prompt({
      type: Severity.Warning,
      message: localize("issueReporterWriteToClipboard", "There is too much data to send to GitHub directly. The data will be copied to the clipboard, please paste it into the GitHub issue page that is opened."),
      buttons: [
        {
          label: localize({ key: "ok", comment: ["&& denotes a mnemonic"] }, "&&OK"),
          run: () => {
            result = true;
          }
        },
        {
          label: localize("cancel", "Cancel"),
          run: () => {
            result = false;
          }
        }
      ]
    });
    return result;
  }
  hasToReload(data) {
    if (data.extensionId && this.extensionIdentifierSet.has(data.extensionId)) {
      this.currentData = data;
      this.issueReporterWindow?.focus();
      return true;
    }
    if (this.issueReporterWindow) {
      this.issueReporterWindow.focus();
      return true;
    }
    return false;
  }
};
IssueFormService = __decorateClass([
  __decorateParam(0, IInstantiationService),
  __decorateParam(1, IAuxiliaryWindowService),
  __decorateParam(2, IMenuService),
  __decorateParam(3, IContextKeyService),
  __decorateParam(4, ILogService),
  __decorateParam(5, IDialogService),
  __decorateParam(6, IHostService),
  __decorateParam(7, IOpenerService),
  __decorateParam(8, IFileService),
  __decorateParam(9, IGitHubUploadService),
  __decorateParam(10, IEditorService),
  __decorateParam(11, IClipboardService)
], IssueFormService);
export {
  IssueFormService,
  extractIssueData
};
