import "./bootstrap-cli.js";
import { configurePortable } from "./bootstrap-node.js";
import { bootstrapESM } from "./bootstrap-esm.js";
import { resolveNLSConfiguration } from "./vs/base/node/nls.js";
import { product } from "./bootstrap-meta.js";
const nlsConfiguration = await resolveNLSConfiguration({ userLocale: "en", osLocale: "en", commit: product.commit, userDataPath: "", nlsMetadataPath: import.meta.dirname });
process.env["VSCODE_NLS_CONFIG"] = JSON.stringify(nlsConfiguration);
configurePortable(product);
process.env["VSCODE_CLI"] = "1";
await bootstrapESM();
await import("./vs/code/node/cli.js");
