import { contextViewMenuCloseAnimation, CONTEXT_VIEW_MENU_MOTION_ANCESTOR_CLASSES, CONTEXT_VIEW_MENU_MOTION_CLASS, CONTEXT_VIEW_MENU_MOTION_CLOSE_ANIMATION_DURATION, CONTEXT_VIEW_MENU_MOTION_CLOSING_CLASS } from "../../../base/browser/ui/contextview/contextview.js";
const WORKBENCH_MENU_MOTION_CLASS = CONTEXT_VIEW_MENU_MOTION_CLASS;
const WORKBENCH_MENU_MOTION_CLOSING_CLASS = CONTEXT_VIEW_MENU_MOTION_CLOSING_CLASS;
const WORKBENCH_MENU_MOTION_CLOSE_ANIMATION_DURATION = CONTEXT_VIEW_MENU_MOTION_CLOSE_ANIMATION_DURATION;
const WORKBENCH_MENU_MOTION_ANCESTOR_CLASSES = CONTEXT_VIEW_MENU_MOTION_ANCESTOR_CLASSES;
const workbenchMenuCloseAnimation = contextViewMenuCloseAnimation;
function getWorkbenchMenuMotionContextMenuOptions(anchor) {
  return {
    getAnchor: () => anchor,
    getMenuClassName: () => WORKBENCH_MENU_MOTION_CLASS,
    closeAnimation: workbenchMenuCloseAnimation
  };
}
export {
  WORKBENCH_MENU_MOTION_ANCESTOR_CLASSES,
  WORKBENCH_MENU_MOTION_CLASS,
  WORKBENCH_MENU_MOTION_CLOSE_ANIMATION_DURATION,
  WORKBENCH_MENU_MOTION_CLOSING_CLASS,
  getWorkbenchMenuMotionContextMenuOptions,
  workbenchMenuCloseAnimation
};
